package openvpn

import "path/filepath"

const (
	defaultBaseDir   = "/data/openvpn/server"
	defaultOutputDir = "/data/openvpn/clients"
)

// Config describes how to locate resources generated by openvpn-install.sh.
type Config struct {
	// BaseDir is the directory where openvpn-install.sh stores server assets
	// (usually /etc/openvpn/server).
	BaseDir string
	// OutputDir controls where client .ovpn files are materialized.
	OutputDir string
	// ScriptPath points to the openvpn-install.sh script (optional, currently used
	// for documentation/logging purposes).
	ScriptPath string
}

func (c *Config) normalize() {
	if c.BaseDir == "" {
		c.BaseDir = defaultBaseDir
	}

	if c.OutputDir == "" {
		c.OutputDir = defaultOutputDir
	}
}

func (c Config) easyRSADir() string {
	return filepath.Join(c.BaseDir, "easy-rsa")
}

func (c Config) clientCommonPath() string {
	return filepath.Join(c.BaseDir, "client-common.txt")
}

func (c Config) tlsAuthKeyPath() string {
	return filepath.Join(c.BaseDir, "tc.key")
}

func (c Config) caCertPath() string {
	return filepath.Join(c.BaseDir, "easy-rsa", "pki", "ca.crt")
}

func (c Config) clientConfigPath(name string) string {
	return filepath.Join(c.OutputDir, name+".ovpn")
}

func (c Config) issuedCertPath(name string) string {
	return filepath.Join(c.BaseDir, "easy-rsa", "pki", "issued", name+".crt")
}

func (c Config) privateKeyPath(name string) string {
	return filepath.Join(c.BaseDir, "easy-rsa", "pki", "private", name+".key")
}

func (c Config) requestPath(name string) string {
	return filepath.Join(c.BaseDir, "easy-rsa", "pki", "reqs", name+".req")
}

func (c Config) crlSourcePath() string {
	return filepath.Join(c.BaseDir, "easy-rsa", "pki", "crl.pem")
}

func (c Config) crlTargetPath() string {
	return filepath.Join(c.BaseDir, "crl.pem")
}
